---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lfx-v2-access-check
  namespace: lfx
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: >-
        Host(`{{ .Values.ingress.hostname }}`) && 
        (Path(`/access-check`) || Path(`/livez`) || Path(`/readyz`))
      priority: 10
      middlewares:
        {{- if .Values.heimdall.enabled }}
        - name: heimdall
        {{- end }}
      services:
        - kind: Service
          name: lfx-v2-access-check
          port: web
