swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /access-check:
        post:
            tags:
                - access-svc
            summary: check-access access-svc
            description: Check access permissions for resource-action pairs
            operationId: access-svc#check-access
            parameters:
                - name: v
                  in: query
                  description: API version
                  required: true
                  type: string
                  enum:
                    - "1"
                - name: Authorization
                  in: header
                  description: JWT token from Heimdall
                  required: true
                  type: string
                - name: Check-AccessRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/AccessSvcCheckAccessRequestBody'
                    required:
                        - requests
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AccessSvcCheckAccessResponseBody'
                        required:
                            - results
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/AccessSvcCheckAccessBadRequestResponseBody'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/AccessSvcCheckAccessUnauthorizedResponseBody'
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /livez:
        get:
            tags:
                - access-svc
            summary: livez access-svc
            description: Check if service is alive
            operationId: access-svc#livez
            produces:
                - text/plain
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: byte
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - access-svc
            summary: Download gen/http/openapi3.json
            operationId: access-svc#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
    /readyz:
        get:
            tags:
                - access-svc
            summary: readyz access-svc
            description: Check if service is ready
            operationId: access-svc#readyz
            produces:
                - text/plain
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: byte
                "503":
                    description: Service Unavailable response.
                    schema:
                        $ref: '#/definitions/AccessSvcReadyzNotReadyResponseBody'
            schemes:
                - http
definitions:
    AccessSvcCheckAccessBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Bad request (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    AccessSvcCheckAccessRequestBody:
        title: AccessSvcCheckAccessRequestBody
        type: object
        properties:
            requests:
                type: array
                items:
                    type: string
                    example: Eius suscipit itaque velit dolorem.
                description: Resource-action pairs to check
                example:
                    - project:123:read
                    - committee:456:write
                minItems: 1
        example:
            requests:
                - project:123:read
                - committee:456:write
        required:
            - requests
    AccessSvcCheckAccessResponseBody:
        title: AccessSvcCheckAccessResponseBody
        type: object
        properties:
            results:
                type: array
                items:
                    type: string
                    example: Qui molestiae illo et enim tempore magnam.
                description: Access check results
                example:
                    - allow
                    - deny
        example:
            results:
                - allow
                - deny
        required:
            - results
    AccessSvcCheckAccessUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Unauthorized (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    AccessSvcReadyzNotReadyResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Service not ready (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
securityDefinitions:
    jwt_header_Authorization:
        type: apiKey
        description: Heimdall authorization
        name: Authorization
        in: header
